### ISSUE TITLE
Feature: option to specify alignment

### ISSUE THREAD

**Issue by armandsLa** [umechanhika/dotted_line#25]
When creating a row of widgets like "<line><text><line>" option to specify line alignment would allow to achieve a better symmetry. Currently the gap between the first line and the text can differ from the text and the second line as it's drawn from left to right.

**Comment by umechanhika** [comment]
@armandsLa 
Thank you for your contribution.

I'm very sorry, but I'm not good at English and I can't understand the meaning of the sentence accurately, so may I ask you to describe it a little more concretely?
If you're talking about screen display, it's easier to understand if you have screenshots.

**Comment by umechanhika** [comment]
@armandsLa 
This issue may have been resolved in #52, so I will close it once.
If you still have problems, please re-open.
