### ISSUE TITLE
Count total dots

### ISSUE THREAD

**Issue by muktabd** [umechanhika/dotted_line#45]
I am not sure this feature has been include with this package or not. If have just let me know if don't so hope developers will add this.
**Have any way to count total dots from  a line ?**

**Comment by umechanhika** [comment]
@muktabd 
Sorry for the late reply.

There is currently no way to get the number of dots using public methods or properties.
But I don't know if it's suitable for your use, it is possible to figure it out from the internal implementation by putting a breakpoint.
Here is the relevant code.
https://github.com/umechanhika/dotted_line/blob/74b85bb2358b63d201087a4486bd0b7f6a8c4ec2/lib/dotted_line.dart#L98-L100

If you don't mind, could you tell me for what purpose you want to count the number of dots?

**Comment by umechanhika** [comment]
@muktabd 
Hi, It's been a long time.

I haven't received a reply in a long time, and I don't feel the need for this feature, so I'm going to close the issue for now.

Please reopen if necessary.

**Comment by muktabd** [comment]
I am sorry too. Recently I busy with another project so I haven't try yet. I will do soon
